## Basic Configuration

baseurl = "https://roblesnotes.com/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Félix Robles"
title = "Félix Robles"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-roblesnotes-com" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Félix Robles"
intro = "Startup & VR Enthusiast, Developer"
description = "Now @nVotes. Previously @Wacom_UK, @Sogeti_Luxembourg and @Airbus_Military.<br/> \"What is F times 5? It's Fleventy-five.\""
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Startup & VR Enthusiast, Developer"
keywords = "startup,vr,enthusiast,developer,programming,javascript,cpp,gpu,scala"

## Social Accounts
[params.social]
github = "Findeton"
instagram = "<username>"
linkedin = "félix-robles-elvira-225b1624"
twitter = "<username>"
facebook = "felix.robles.568"
google = "+FélixRobles"
stackoverflow = "<username>"
email = "felrobelv AT gmail DOT com"

## Extras
[params.extra]
copyright = "© 2017. Félix Robles. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
